const actionConstants = {
  COMPLETE: 'COMPLETE',
  UPDATE_EMAIL: 'UPDATE_EMAIL',
  UPDATE_PASSWORD: 'UPDATE_PASSWORD',
  UPDATE_FNAME: 'UPDATE_FNAME',
  UPDATE_LNAME: 'UPDATE_LNAME',
  UPDATE_ADDRESS: 'UPDATE_ADDRESS',
  UPDATE_COUNTRY_CODE: 'UPDATE_COUNTRY_CODE',
  UPDATE_PHONE_NUMBER: 'UPDATE_PHONE_NUMBER',
  UPDATE_TC: 'UPDATE_TC',
};

export default actionConstants;
